#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# OMARCHY-STYLE UNIFIED DESKTOP THEME GENERATOR
# Wallpaper → Matugen → colors.toml (Source of Truth)
# Synchronizes: Quickshell, KDE/Qt, GTK 3/4, Hyprland, and Kitty
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

IMG="${1:-}"

# Fallback to saved wallpaper if argument is empty
if [ -z "$IMG" ]; then
    if [ -f "/home/aran/.config/quickshell/wallpaper.txt" ]; then
        IMG=$(cat /home/aran/.config/quickshell/wallpaper.txt | tr -d '\n')
    else
        IMG="/home/aran/Pictures/Wallpapers/blueeve.jpg"
    fi
fi

# Clean file:// URI scheme
IMG="${IMG#file://}"

if [ ! -f "$IMG" ]; then
    echo "Wallpaper file not found: $IMG" >&2
    exit 1
fi

CONFIG_FILE="/home/aran/.config/matugen/config.toml"

# 1. Run Matugen to generate all configured templates
matugen -c "$CONFIG_FILE" image "$IMG" --source-color-index 0

THEME_TOML="/home/aran/.config/theme/colors.toml"
QS_THEME_DIR="/home/aran/.config/quickshell/theme"
mkdir -p "$QS_THEME_DIR"

# 2. Maintain symlink to colors.toml in Quickshell
ln -sf "$THEME_TOML" "$QS_THEME_DIR/colors.toml"

COLORS_JSON="$QS_THEME_DIR/colors.json"

# 2b. macOS-Style Adaptive Menu Bar Luminance Analysis (Sample top 36px)
python3 -c "
import json
from PIL import Image

try:
    with Image.open('$IMG') as im:
        im = im.convert('RGB')
        w, h = im.size
        sample_h = max(36, int(h * 0.04))
        crop = im.crop((0, 0, w, sample_h)).resize((100, 10))
        b = crop.tobytes()
        total_lum = sum(0.2126 * b[i] + 0.7152 * b[i+1] + 0.0722 * b[i+2] for i in range(0, len(b), 3))
        avg_lum = total_lum / (len(b) / 3) / 255.0
        is_light = avg_lum > 0.55

        with open('$COLORS_JSON', 'r') as f:
            data = json.load(f)

        data['bar_is_light'] = is_light
        data['bar_lum'] = round(avg_lum, 3)

        with open('$COLORS_JSON', 'w') as f:
            json.dump(data, f, indent=2)
except Exception:
    pass
" 2>/dev/null || true

# 3. Extract Primary & Tertiary colors
if [ -f "$COLORS_JSON" ] && command -v jq >/dev/null 2>&1; then
    PRIMARY_HEX=$(jq -r '.primary' "$COLORS_JSON")
    PRIMARY_STRIPPED="${PRIMARY_HEX#'#'}"
    TERTIARY_HEX=$(jq -r '.tertiary' "$COLORS_JSON")
    TERTIARY_STRIPPED="${TERTIARY_HEX#'#'}"

    # Extract RGB components for KDE kdeglobals
    R=$((16#${PRIMARY_STRIPPED:0:2}))
    G=$((16#${PRIMARY_STRIPPED:2:2}))
    B=$((16#${PRIMARY_STRIPPED:4:2}))
    PRIMARY_RGB="$R,$G,$B"

    # Set new AccentColor and disable accentColorFromWallpaper BEFORE applying scheme
    if command -v kwriteconfig6 >/dev/null 2>&1; then
        kwriteconfig6 --file kdeglobals --group General --key AccentColor "$PRIMARY_RGB" 2>/dev/null || true
        kwriteconfig6 --file kdeglobals --group General --key accentColorFromWallpaper "false" 2>/dev/null || true
        kwriteconfig6 --file kdeglobals --group General --key ColorScheme "" 2>/dev/null || true
    fi

    # Ensure colors.lua exists for Hyprland config reloads/reboots
    cat <<EOF > /home/aran/.config/hypr/colors.lua
-- Auto-generated by Matugen. Do not edit directly.
return {
    primary = "${PRIMARY_HEX}",
    tertiary = "${TERTIARY_HEX}",
    active_border = {
        colors = {
            "rgba(${PRIMARY_STRIPPED}ee)",
            "rgba(${TERTIARY_STRIPPED}ee)"
        },
        angle = 45
    },
    inactive_border = "rgba(595959aa)",
}
EOF

    # 4. Update Hyprland window border gradients live
    if command -v hyprctl >/dev/null 2>&1; then
        hyprctl eval "hl.config({ general = { col = { active_border = { colors = {'rgba(${PRIMARY_STRIPPED}ee)', 'rgba(${TERTIARY_STRIPPED}ee)'}, angle = 45 } } } })" >/dev/null 2>&1 || true
    fi
fi

# 5. Apply KDE / Qt Color Scheme (reads the newly updated AccentColor)
if command -v plasma-apply-colorscheme >/dev/null 2>&1; then
    plasma-apply-colorscheme Matugen >/dev/null 2>&1 || true
fi

# Notify running Dolphin instances to refresh view
if command -v qdbus6 >/dev/null 2>&1; then
    for svc in $(qdbus6 2>/dev/null | grep -E '^ org\.kde\.dolphin-' || true); do
        qdbus6 "${svc## }" /dolphin/Dolphin_1/actions/view_redisplay trigger >/dev/null 2>&1 || true
    done
fi

# 5b. Generate Qt6CT Color Scheme & trigger live reload for Qt6 processes
python3 -c "
import json, os

colors_json_path = os.path.expanduser('$COLORS_JSON')
if not os.path.exists(colors_json_path):
    exit(0)

try:
    with open(colors_json_path) as f:
        c = json.load(f)

    def h(hex_str):
        return hex_str.replace('#', '').lower()

    window_text = '#ff' + h(c.get('on_surface', '#ffffff'))
    btn = '#ff' + h(c.get('surface_container_high', '#2b3035'))
    light = '#ff' + h(c.get('surface_bright', '#3c4146'))
    midlight = '#ff' + h(c.get('surface_container_highest', '#32373c'))
    dark = '#ff' + h(c.get('surface_container_low', '#1e2226'))
    mid = '#ff' + h(c.get('outline_variant', '#49454f'))
    text = '#ff' + h(c.get('on_surface', '#ffffff'))
    bright_text = '#ff' + h(c.get('on_primary', '#ffffff'))
    btn_text = '#ff' + h(c.get('on_surface', '#ffffff'))
    base = '#ff' + h(c.get('surface_dim', '#14181b'))
    window = '#ff' + h(c.get('surface', '#191d20'))
    shadow = '#ff000000'
    highlight = '#ff' + h(c.get('primary', '#80d5cf'))
    highlighted_text = '#ff' + h(c.get('on_primary', '#003735'))
    link = '#ff' + h(c.get('primary', '#80d5cf'))
    link_visited = '#ff' + h(c.get('secondary', '#b0cccb'))
    alt_base = '#ff' + h(c.get('surface_container', '#222629'))
    tooltip_base = '#ff' + h(c.get('surface_container_highest', '#32373c'))
    tooltip_text = '#ff' + h(c.get('on_surface', '#ffffff'))
    placeholder = '#ff' + h(c.get('outline', '#8e918f'))
    accent = '#ff' + h(c.get('primary', '#80d5cf'))

    palette = [
        window_text, btn, light, midlight, dark, mid, text, bright_text, btn_text,
        base, window, shadow, highlight, highlighted_text, link, link_visited,
        alt_base, tooltip_base, tooltip_text, placeholder, accent
    ]
    active_str = ', '.join(palette)
    inactive_str = active_str
    disabled_str = active_str.replace('#ff', '#80')

    out_dir = os.path.expanduser('~/.config/qt6ct/colors')
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, 'matugen.conf')

    with open(out_file, 'w') as f:
        f.write('[ColorScheme]\n')
        f.write(f'active_colors={active_str}\n')
        f.write(f'disabled_colors={disabled_str}\n')
        f.write(f'inactive_colors={inactive_str}\n')
except Exception:
    pass
" 2>/dev/null || true

# Trigger QFileSystemWatcher in Qt6CT
touch ~/.config/qt6ct/qt6ct.conf 2>/dev/null || true

# 5. Reload GTK Apps via xsettingsd & gsettings
if command -v pkill >/dev/null 2>&1; then
    pkill -HUP xsettingsd 2>/dev/null || true
fi

# 6. Reload Kitty Terminal instances
if command -v pkill >/dev/null 2>&1; then
    pkill -USR1 kitty 2>/dev/null || true
fi

echo "✓ Omarchy-style theme generated and applied across Quickshell, KDE, GTK, Hyprland & Kitty for $IMG"
