-- Auto-generated by Matugen. Do not edit directly.
return {
    primary = "#bac3ff",
    tertiary = "#e5bad8",
    active_border = {
        colors = {
            "rgba(bac3ffee)",
            "rgba(e5bad8ee)"
        },
        angle = 45
    },
    inactive_border = "rgba(595959aa)",
}
