-- Auto-generated by Matugen. Do not edit directly.
return {
    primary = "{{colors.primary.default.hex}}",
    tertiary = "{{colors.tertiary.default.hex}}",
    surface = "{{colors.surface.default.hex}}",
    active_border = {
        colors = {
            "rgba({{colors.primary.default.hex_stripped}}ee)",
            "rgba({{colors.tertiary.default.hex_stripped}}ee)"
        },
        angle = 45
    },
    inactive_border = "rgba(595959aa)",
}
