$matugen_primary = rgb({{colors.primary.default.hex_stripped}})
$matugen_tertiary = rgb({{colors.tertiary.default.hex_stripped}})
$matugen_surface = rgb({{colors.surface.default.hex_stripped}})
$matugen_surface_container = rgb({{colors.surface_container_highest.default.hex_stripped}})
